const menu = [
    {
      id: 1,
      title: 'Minjon rozen torta',
      category: 'minjon',
      price: 1600,
      img: './images/img-1.jpg',
      desc: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. `,
    },
    {
      id: 2,
      title: 'Cheesecake',
      category: 'torta',
      price: 1000,
      img: './images/img-2.jpeg',
      desc: `Cheesecake is a sweet dessert consisting of one or more layers. The main, and thickest, layer consists of a mixture of a soft, fresh cheese (typically cottage cheese, cream cheese or ricotta), eggs, and sugar. `,
    },
    {
      id: 3,
      title: 'Baron torta',
      category: 'torta',
      price: 1000,
      img: './images/img-3.jpeg',
      desc: `The cake consists of 3-4 layers of sponge cake, generally fine although I have seen some with thicker sponge cakes, made with egg whites, sugar, cocoa powder and ground almond or flour. `,
    },
    {
      id: 4,
      title: 'Lesnik torta',
      category: 'torta',
      price: 1000,
      img: './images/img-4.jpg',
      desc: `Lagane, vazdušaste lešnik kore i krem od belom čokoladom sa mlevenim lešnicima, preliveni mlečnom čokoladom sa nežnom notom vanile. `,
    },
    {
      id: 5,
      title: 'Minjon voćna torta',
      category: 'minjon',
      price: 1600,
      img: './images/img-5.jpg',
      desc: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.`,
    },
    {
      id: 6,
      title: 'Minjon torta malina-plazma',
      category: 'minjon',
      price: 1600,
      img: './images/img-6.jpg',
      desc: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.`,
    },
    {
      id: 7,
      title: 'Minjon sa makom',
      category: 'minjon',
      price: 1600,
      img: './images/img-7.jpg',
      desc: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. `,
    },
    {
      id: 8,
      title: 'Plazma torta',
      category: 'torta',
      price: 1000,
      img: './images/img-8.jpg',
      desc: `Čoko plazma torta koja može da bude dečija, rođendanska a i za svaki dan, reklo bi se univerzalna. Pravila sam pola mere pa tako i pišem sastojke  `,
    },
    {
      id: 9,
      title: 'Reforma torta',
      category: 'torta',
      price: 1000,
      img: './images/img-9.jpeg',
      desc: `Reform torta je urnebesno fina čokoladna torta sa orasima prilično jednostavne izrade`,
    },
  ];
  export default menu;